name: 'dbt_tests'
version: '1.0.0'
config-version: 2

profile: 'galaxy'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_tests:
    raw:
      schema: raw
    stg:
      schema: stg
    mart:
      schema: mart
